	SUBROUTINE POLE (A1,D1,A2,D2)

	COMMON AZ,TOA,RC,X,Y,RAD,A,D,PI,P2

	T = TAN(D1) * SIN(A1) - TAN(D2) * SIN(A2)
	B = TAN(D1) * COS(A1) - TAN(D2) * COS(A2)
	AZ = ATAN (T/B)
	B = ATAN (TAN(D1)*SIN(AZ-A1))
	TOA = P2-B
	IF (TOA .GT. P2) THEN
		AZ = AZ+PI
		TOA = PI-TOA
	ENDIF
	END
